include:
  - board: seeeduino_xiao_ble
    shield: Pyuron_R
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: Pyuron_L
  - board: seeeduino_xiao_ble
    shield: settings_reset
 
